# Generated by Django 3.0.5 on 2021-02-24 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='assinmain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assin_created', models.DateTimeField(auto_created=True)),
                ('assin_due', models.DateTimeField()),
                ('assin_head', models.CharField(max_length=50)),
                ('assin_desc', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='class_dat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectcode', models.CharField(default='nil', max_length=20)),
                ('cteacher', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='grades_dat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_title', models.CharField(max_length=30)),
                ('exam_grades', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='stu_data',
            fields=[
                ('grno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('attendence', models.CharField(max_length=40)),
                ('feestatus', models.CharField(max_length=90)),
                ('assin_id', models.CharField(max_length=20, unique=True)),
                ('assin_ls', models.CharField(max_length=130)),
                ('assin_status', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('full_name', models.CharField(max_length=191)),
                ('phone_no', models.CharField(max_length=12)),
                ('emailid', models.CharField(max_length=20)),
                ('Address', models.CharField(max_length=191)),
                ('grno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='teacher_dat',
            fields=[
                ('teacher_fullname', models.CharField(max_length=30)),
                ('teacher_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Fruit',
        ),
        migrations.AddField(
            model_name='stu_data',
            name='studentdetails',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Student'),
        ),
        migrations.AddField(
            model_name='class_dat',
            name='subject',
            field=models.ManyToManyField(to='home.teacher_dat'),
        ),
        migrations.AddField(
            model_name='assinmain',
            name='class_dat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.class_dat'),
        ),
    ]
